# 站点&个人信息配置
title: 托尼吹雪
author: 陆健
description: 一个没有脱离低级趣味(装13)的人...
keyword: engineer tony
favicon: /tony.ico
avatar: /tony.png
slogan: 就这么吹来吹去~
wechat_qr: /img/wechat-tony.jpg
github_url: https://github.com/lucups

# 菜单配置
menu:
    Home: /
    Archives: /archives/
    Categories: /categories/
    Tags: /tags/
    About: /about/
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true
code_style: vs.css

# Sidebar
sidebar: right
widgets:
    - category
    - tag
    - tagcloud
    - archive
    - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
twitter:
google_plus:
fb_admins:
fb_app_id:
